using UnityEngine;
using UnityEngine.SceneManagement;

namespace PG
{
    /// <summary>
    /// Startup validation - NOT a second way to build the game.
    ///
    /// The one source of truth is Assets/Scenes/Game.unity plus PlayerShip.prefab,
    /// both generated by PGBootstrap. If the player starts in any other scene,
    /// this shows an explicit error instead of silently assembling a reduced,
    /// model-less copy of the game (which the previous version did).
    /// </summary>
    public static class RuntimeBootstrap
    {
        public const string GameSceneName = "Game";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void ValidateStartupScene()
        {
            var scene = SceneManager.GetActiveScene();
            // The test runner's own init scenes are not game scenes.
            if (scene.name.StartsWith("InitTestScene")) return;
            if (Object.FindAnyObjectByType<GameManager>() != null) return;

            Debug.LogWarning("[PG] Startup scene '" + scene.name + "' is not the game scene. " +
                             "Open Assets/Scenes/Game.unity (Tools > PG > Build Game Scene regenerates it).");
            var go = new GameObject("PG_InvalidStartupScene");
            go.AddComponent<InvalidSceneNotice>().sceneName = scene.name;
        }
    }

    /// <summary>On-screen explanation shown only when the wrong scene was started.</summary>
    public class InvalidSceneNotice : MonoBehaviour
    {
        public string sceneName;

        void OnGUI()
        {
            var r = new Rect(Screen.width * 0.5f - 320, Screen.height * 0.5f - 60, 640, 120);
            GUI.Box(r, "");
            GUI.Label(new Rect(r.x + 16, r.y + 16, r.width - 32, r.height - 32),
                "This is not the game scene (" + sceneName + ").\n" +
                "Start Assets/Scenes/Game.unity - it is the only startup scene of Sable Reach.");
        }
    }
}
